/*-
 * WSDL stubs for:  AvlService.wsdl
 *   Generated by:  michael
 *           Date:  Tue Mar 24 17:57:22 2009
 *        Emitter:  Objective-C
 */

#import "AvlService.h"

/*-
 *   Method Name:  getAgencies
 * Documentation:  <no documentation>
 */
@implementation getAgencies
- (id) resultValue
{
    return [[super getResultDictionary] objectForKey: @"ns1:getAgenciesReturn"];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://ws.its.washington.edu:9090/transit/avl/services/AvlService"            
                 methodName: @"getAgencies"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: @""            
            methodNamespace: @"http://avl.transit.ws.its.washington.edu"            
        ];        
}

@end; /* getAgencies */


/*-
 *   Method Name:  getTime
 * Documentation:  <no documentation>
 */
@implementation getTime
- (id) resultValue
{
    return [[super getResultDictionary] objectForKey: @"ns1:getTimeReturn"];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://ws.its.washington.edu:9090/transit/avl/services/AvlService"            
                 methodName: @"getTime"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
				 style: (NSString*) kWSSOAPStyleRPC
                 soapAction: @""            
            methodNamespace: @"http://avl.transit.ws.its.washington.edu"            
        ];        
}
@end; /* getTime */


/*-
 *   Method Name:  getLatestByRoute
 * Documentation:  <no documentation>
 */
@implementation getLatestByRoute
- (void) setParameters:(NSString*) in_in0 in_in1:(SInt32) in_in1
{
    id _paramValues[] = {    
        in_in0,        
        [NSNumber numberWithInt: in_in1],        
    };    
    NSString* _paramNames[] = {    
        @"in0",        
        @"in1",        
    };    
    [super setParameters:2 values: _paramValues names: _paramNames];    
}

- (id) resultValue
{
    return [[super getResultDictionary] objectForKey: @"ns1:getLatestByRouteReturn"];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://ws.its.washington.edu:9090/transit/avl/services/AvlService"            
                 methodName: @"getLatestByRoute"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: @""            
            methodNamespace: @"http://avl.transit.ws.its.washington.edu"            
        ];        
}

@end; /* getLatestByRoute */



@implementation AvlService

+ (id) getAgencies
{
    id result = NULL;    
    getAgencies* _invocation = [[getAgencies alloc] init];    
    result = [[_invocation resultValue] retain];    
    [_invocation release];    
    return result;    
}


+ (id) getTime
{
    id result = NULL;    
    getTime* _invocation = [[getTime alloc] init];    
    result = [[_invocation resultValue] retain];    
    [_invocation release];    
    return result;    
}


+ (id) getLatestByRoute:(NSString*) in_in0 in_in1:(SInt32) in_in1
{
    id result = NULL;    
    getLatestByRoute* _invocation = [[getLatestByRoute alloc] init];    
    [_invocation setParameters: in_in0 in_in1:in_in1];    
    result = [[_invocation resultValue] retain];    
    [_invocation release];    
    return result;    
}



@end;


/*-
 * End of WSDL document at AvlService.wsdl
 */
