/*-
 * WSDL stubs for:  Mybus.wsdl
 *   Generated by:  michael
 *           Date:  Thu Jun 25 07:12:21 2009
 *        Emitter:  Objective-C
 */

#import "MyBus.h"
#if 0
/*-
 *   Method Name:  currentTimeMillis
 * Documentation:  <no documentation>
 */
@implementation currentTimeMillis
- (void) setParameters:(CFTypeRef /* Complex type http://dotnet.ws.its.washington.edu|currentTimeMillis */) in_parameters
{
    id _paramValues[] = {    
        in_parameters,        
    };    
    NSString* _paramNames[] = {    
        @"parameters",        
    };    
    [super setParameters:1 values: _paramValues names: _paramNames];    
}

- (id) resultValue
{
    return [[super getResultDictionary] objectForKey: @"parameters"];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://ws.its.washington.edu/Mybus/Mybus.asmx"            
                 methodName: @"currentTimeMillis"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: @"http://dotnet.ws.its.washington.edu/currentTimeMillis"            
            methodNamespace: NULL /* No Method Namespace specified */            
        ];        
}

@end; /* currentTimeMillis */

/*-
 *   Method Name:  getEventEstimates
 * Documentation:  Departure time estimates for a given location within a specified
 *                 time interval
 */
@implementation getEventEstimates
- (void) setParameters:(CFTypeRef /* Complex type http://dotnet.ws.its.washington.edu|getEventEstimatesIII */) in_parameters
{
    id _paramValues[] = {    
        in_parameters,        
    };    
    NSString* _paramNames[] = {    
        @"parameters",        
    };    
    [super setParameters:1 values: _paramValues names: _paramNames];    
}

- (id) resultValue
{
    return [[super getResultDictionary] objectForKey: @"parameters"];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://ws.its.washington.edu/Mybus/Mybus.asmx"            
                 methodName: @"getEventEstimates"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: @"http://dotnet.ws.its.washington.edu/getEventEstimatesIII"            
            methodNamespace: NULL /* No Method Namespace specified */            
        ];        
}

@end; /* getEventEstimates */


/*-
 *   Method Name:  currentTimeMillis
 * Documentation:  <no documentation>
 */
@implementation currentTimeMillis
- (id) resultValue
{
    return [[super getResultDictionary] objectForKey: @"Body"];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://ws.its.washington.edu/Mybus/Mybus.asmx"            
                 methodName: @"currentTimeMillis"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
            // missing encoding style - defaulting to RPC            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: nil /* No SOAPAction header needed */            
            methodNamespace: NULL /* No Method Namespace specified */            
        ];        
}

@end; /* currentTimeMillis */


/*-
 *   Method Name:  getEventEstimates
 * Documentation:  Departure time estimates for a given location within a specified
 *                 time interval
 */
@implementation getEventEstimates
- (void) setParameters:(NSString*) in_timepoint in_loTime:(NSString*) in_loTime in_hiTime:(NSString*) in_hiTime
{
    id _paramValues[] = {    
        in_timepoint,        
        in_loTime,        
        in_hiTime,        
    };    
    NSString* _paramNames[] = {    
        @"timepoint",        
        @"loTime",        
        @"hiTime",        
    };    
    [super setParameters:3 values: _paramValues names: _paramNames];    
}

- (id) resultValue
{
    return [[super getResultDictionary] objectForKey: @"Body"];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://ws.its.washington.edu/Mybus/Mybus.asmx"            
                 methodName: @"getEventEstimates"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
            // missing encoding style - defaulting to RPC            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: nil /* No SOAPAction header needed */            
            methodNamespace: NULL /* No Method Namespace specified */            
        ];        
}

@end; /* getEventEstimates */
#endif

/*-
 *   Method Name:  currentTimeMillis
 * Documentation:  <no documentation>
 */
@implementation currentTimeMillis
- (id) resultValue
{
    return [[super getResultDictionary] objectForKey: @"Body"];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://ws.its.washington.edu/Mybus/Mybus.asmx"            
                 methodName: @"currentTimeMillis"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
            // missing encoding style - defaulting to RPC            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: nil /* No SOAPAction header needed */            
            methodNamespace: NULL /* No Method Namespace specified */            
        ];        
}

@end; /* currentTimeMillis */


/*-
 *   Method Name:  getEventEstimates
 * Documentation:  Departure time estimates for a given location within a specified
 *                 time interval
 */
@implementation getEventEstimates
- (void) setParameters:(NSString*) in_timepoint in_loTime:(NSString*) in_loTime in_hiTime:(NSString*) in_hiTime
{
    id _paramValues[] = {    
        in_timepoint,        
        in_loTime,        
        in_hiTime,        
    };    
    NSString* _paramNames[] = {    
        @"timepoint",        
        @"loTime",        
        @"hiTime",        
    };    
    [super setParameters:3 values: _paramValues names: _paramNames];    
}

- (id) resultValue
{
    return [[super getResultDictionary] objectForKey: @"Body"];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
#if 0
    return [self createInvocationRef    
               /*endpoint*/: @"http://ws.its.washington.edu/Mybus/Mybus.asmx"            
                 methodName: @"getEventEstimates"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
            // missing encoding style - defaulting to RPC            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: nil /* No SOAPAction header needed */            
            methodNamespace: NULL /* No Method Namespace specified */            
        ];        
#endif

    return [self createInvocationRef    
			/*endpoint*/: @"http://ws.its.washington.edu/Mybus/Mybus.asmx"            
			methodName: @"getEventEstimates"            
			protocol: (NSString*) kWSSOAP2001Protocol            
			style: (NSString*) kWSSOAPStyleRPC            
			soapAction: @"http://dotnet.ws.its.washington.edu/getEventEstimatesIII"            
            methodNamespace: NULL /* No Method Namespace specified */            
			];        
}

@end; /* getEventEstimates */



@implementation MybusDotNetService

//+ (id) currentTimeMillis:(CFTypeRef /* Complex type http://dotnet.ws.its.washington.edu|currentTimeMillis */) in_parameters
+ (id) currentTimeMillis
{
    id result = NULL;    
    currentTimeMillis* _invocation = [[currentTimeMillis alloc] init];    
//    [_invocation setParameters: in_parameters];    
    result = [[_invocation resultValue] retain];    
    [_invocation release];    
    return result;    
}


//+ (id) getEventEstimates:(CFTypeRef /* Complex type http://dotnet.ws.its.washington.edu|getEventEstimatesIII */) in_parameters
+ (id) getEventEstimates:(NSString*) in_timepoint in_loTime:(NSString*) in_loTime in_hiTime:(NSString*) in_hiTime;
{
    id result = NULL;    
    getEventEstimates* _invocation = [[getEventEstimates alloc] init];    
    [_invocation setParameters:in_timepoint in_loTime:in_loTime in_hiTime:in_hiTime];    
    result = [[_invocation resultValue] retain];    
    [_invocation release];    
    return result;    
}



@end;


/*-
 * End of WSDL document at Mybus.wsdl
 */
