/*-
 * WSDL stubs for:  Mybus.wsdl
 *   Generated by:  michael
 *           Date:  Thu Jun 25 07:12:21 2009
 *        Emitter:  Objective-C
 */

#ifndef __MyBus__
#define __MyBus__

#import <CoreServices/CoreServices.h>
#import <Foundation/Foundation.h>
#import "WSGeneratedObj.h"

/*-
 *   Web Service:  MybusDotNet
 * Documentation:  Real-Time Bus Departure Times for Seattle
 */
#if 0
/*-
 *   Method Name:  currentTimeMillis
 * Documentation:  <no documentation>
 */

@interface currentTimeMillis : WSGeneratedObj

// update the parameter list for the invocation.
- (void) setParameters:(CFTypeRef /* Complex type http://dotnet.ws.its.washington.edu|currentTimeMillis */) in_parameters;

// result returns an id from the reply dictionary as specified by the WSDL.
- (id) resultValue;

@end; /* currentTimeMillis */

/*-
 *   Method Name:  getEventEstimates
 * Documentation:  Departure time estimates for a given location within a specified
 *                 time interval
 */

@interface getEventEstimates : WSGeneratedObj

// update the parameter list for the invocation.
- (void) setParameters:(CFTypeRef /* Complex type http://dotnet.ws.its.washington.edu|getEventEstimatesIII */) in_parameters;

// result returns an id from the reply dictionary as specified by the WSDL.
- (id) resultValue;

@end; /* getEventEstimates */


/*-
 *   Method Name:  currentTimeMillis
 * Documentation:  <no documentation>
 */

@interface currentTimeMillis : WSGeneratedObj

// No parameters for this method

// result returns an id from the reply dictionary as specified by the WSDL.
- (id) resultValue;

@end; /* currentTimeMillis */


/*-
 *   Method Name:  getEventEstimates
 * Documentation:  Departure time estimates for a given location within a specified
 *                 time interval
 */

@interface getEventEstimates : WSGeneratedObj

// update the parameter list for the invocation.
- (void) setParameters:(NSString*) in_timepoint in_loTime:(NSString*) in_loTime in_hiTime:(NSString*) in_hiTime;

// result returns an id from the reply dictionary as specified by the WSDL.
- (id) resultValue;

@end; /* getEventEstimates */
#endif

/*-
 *   Method Name:  currentTimeMillis
 * Documentation:  <no documentation>
 */

@interface currentTimeMillis : WSGeneratedObj

// No parameters for this method

// result returns an id from the reply dictionary as specified by the WSDL.
- (id) resultValue;

@end; /* currentTimeMillis */

/*-
 *   Method Name:  getEventEstimates
 * Documentation:  Departure time estimates for a given location within a specified
 *                 time interval
 */

@interface getEventEstimates : WSGeneratedObj

// update the parameter list for the invocation.
- (void) setParameters:(NSString*) in_timepoint in_loTime:(NSString*) in_loTime in_hiTime:(NSString*) in_hiTime;

// result returns an id from the reply dictionary as specified by the WSDL.
- (id) resultValue;

@end; /* getEventEstimates */


/*-
 * Web Service:  MybusDotNet
 */
@interface MybusDotNetService : NSObject 

+ (id) currentTimeMillis;
+ (id) getEventEstimates:(NSString*) in_timepoint in_loTime:(NSString*) in_loTime in_hiTime:(NSString*) in_hiTime;

@end;


#endif /* __MyBus__ */
/*-
 * End of WSDL document at Mybus.wsdl
 */
