/*-
 * WSDL stubs for:  AvlService.wsdl
 *   Generated by:  michael
 *           Date:  Thu Jun 25 11:36:27 2009
 *        Emitter:  Objective-C
 */

#ifndef __AvlSvc__
#define __AvlSvc__

#import <CoreServices/CoreServices.h>
#import <Foundation/Foundation.h>
#import "WSGeneratedObj.h"

/*-
 *   Web Service:  AvlService
 * Documentation:  <not documented>
 */
/*-
 *   Method Name:  getAgencies
 * Documentation:  <no documentation>
 */

@interface getAgencies : WSGeneratedObj

// No parameters for this method

// result returns an id from the reply dictionary as specified by the WSDL.
- (id) resultValue;

@end; /* getAgencies */


/*-
 *   Method Name:  getTime
 * Documentation:  <no documentation>
 */

@interface getTime : WSGeneratedObj

// No parameters for this method

// result returns an id from the reply dictionary as specified by the WSDL.
- (id) resultValue;

@end; /* getTime */


/*-
 *   Method Name:  getLatestByRoute
 * Documentation:  <no documentation>
 */

@interface getLatestByRoute : WSGeneratedObj

// update the parameter list for the invocation.
- (void) setParameters:(NSString*) in_in0 in_in1:(SInt32) in_in1;

// result returns an id from the reply dictionary as specified by the WSDL.
- (id) resultValue;

@end; /* getLatestByRoute */


/*-
 * Web Service:  AvlService
 */
@interface AvlService : NSObject 

+ (id) getAgencies;
+ (id) getTime;
+ (id) getLatestByRoute:(NSString*) in_in0 in_in1:(SInt32) in_in1;

@end;


#endif /* __AvlSvc__ */
/*-
 * End of WSDL document at AvlService.wsdl
 */
